#!/usr/bin/env node
const { exec } = require("child_process");

exec("node . --start & node php", (error, stdout, stderr) => {
    if (error) {
        console.log(`error: ${error.message}`);
        return;
    }
    if (stderr) {
        console.log(`stderr: ${stderr}`);
        return;
    }
    console.log(`stdout: ${stdout}`);
});

console.log("InkStatus Web Server & PHP Web Server have started!")
console.log("View the Web Server on http://localhost:5000")